import type { Product } from "../types";

export const PRODUCTS: Product[] = [
  {
    id: "p-1",
    slug: "premium-wireless-headphones",
    title: "Premium Wireless Headphones",
    description: "High-fidelity sound with noise cancellation and 30-hour battery.",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.6,
    ratingCount: 128,
    images: [{ url: "/images/dolceG.jpg", alt: "Premium wireless headphones" }],
    tags: ["audio", "wireless"],
    inStock: true,
  },
  {
    id: "p-2",
    slug: "stylish-sunglasses",
    title: "Stylish Sunglasses",
    description: "UV400 protection with scratch-resistant lenses.",
    price: 45.5,
    rating: 4.2,
    ratingCount: 64,
    images: [{ url: "/images/dolceG.jpg", alt: "Stylish sunglasses" }],
    tags: ["accessories"],
    inStock: true,
  },
  {
    id: "p-3",
    slug: "eco-tote-bag",
    title: "Eco Tote Bag",
    description: "Durable cotton tote bag for everyday carry.",
    price: 22.0,
    rating: 4.8,
    ratingCount: 210,
    images: [{ url: "/images/dolceG.jpg", alt: "Eco tote bag" }],
    tags: ["bags", "eco"],
    inStock: true,
  },
  {
    id: "p-4",
    slug: "travel-water-bottle",
    title: "Travel Water Bottle",
    description: "Insulated stainless steel, keeps drinks cold 24h.",
    price: 29.99,
    rating: 4.4,
    ratingCount: 95,
    images: [{ url: "/images/dolceG.jpg", alt: "Travel water bottle" }],
    tags: ["outdoors"],
    inStock: true,
  },
] as const;

