import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/layout/Footer";
import Header from "../components/layout/Header";
import { fonts } from "../constants";

export const metadata: Metadata = {
  title: "LionDen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${fonts.sans.variable} ${fonts.display.variable} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
